//9

import { pool } from "./db";
import { Song, SongInput } from "../domain/song";
import { randomUUID } from "crypto";

/**
 * Maps DB rows to domain objects
 * Keeps persistence concerns isolated
 */
function mapRow(row: any): Song {
  return {
    id: row.id,
    title: row.title,
    artist: row.artist,
    url: row.url ?? null
  };
}

export async function findAll(): Promise<Song[]> {
  const [rows] = await pool.query(
    `SELECT id, title, artist, url
     FROM songs`
  );

  return (rows as any[]).map(mapRow);
}

export async function findById(id: string): Promise<Song | null> {
  const [rows] = await pool.query(
    `SELECT id, title, artist, url
     FROM songs
     WHERE id = ?`,
    [id]
  );

  const result = rows as any[];
  return result.length ? mapRow(result[0]) : null;
}

export async function insert(data: SongInput): Promise<Song> {
  /**
   * UUID generated by application
   * Safe under concurrency
   */
  const id = randomUUID();

  await pool.query(
    `INSERT INTO songs (id, title, artist, url)
     VALUES (?, ?, ?, ?)`,
    [id, data.title, data.artist, data.url ?? null]
  );

  /**
   * No SELECT required
   * We already know exactly what was inserted
   */
  return {
    id,
    title: data.title!,
    artist: data.artist!,
    url: data.url ?? null
  };
}

export async function update(
  id: string,
  data: SongInput
): Promise<boolean> {
    //partial update
    //when field is undefined, diver convert it to null. coalease pick the original value
  const [result] = await pool.query(
    `UPDATE songs
     SET
       title  = COALESCE(?, title),
       artist = COALESCE(?, artist),
       url    = COALESCE(?, url)
     WHERE id = ?`,
    [data.title, data.artist, data.url, id]
  );

  // mysql2 typing gap
  // @ts-ignore
  return result.affectedRows > 0;
}

export async function remove(id: string): Promise<boolean> {
  const [result] = await pool.query(
    `DELETE FROM songs WHERE id = ?`,
    [id]
  );

  // @ts-ignore
  return result.affectedRows > 0;
}
