//12.2 
// Goal: store correlation id in request context
//       Every layer (logger, controller, service) can read rquest context 
// flow:
//      try reading correlation id from request
//          eg, if it was generated by auth service before calling spotify service\
//          eg, if it was generated by api gw 
//          eg, if this http call was triggered by other http call that triggered this call etc
//      generate correlation id if not given in request 
//      Store correlation id in request context 
//      Start processing the requst with that context
// Clean:
//  tied to fw (express), not fw- agnostic
//  Business code remains framework-agnostic

import { Request, Response, NextFunction } from 'express';
import { withRequestContext, requestContext } from '../../utils/request-context/request-context';
import { randomUUID } from 'node:crypto';
const CORRELATION_ID_HEADER = 'x-correlation-id';

export function requestContextMiddleware(req: Request, res: Response, next: NextFunction) {
  // 1. Try to read from incoming request headers
  const incomingCorrelationId =
    req.headers[CORRELATION_ID_HEADER] ||
    req.headers[CORRELATION_ID_HEADER.toLowerCase()];

  // 2. Generate new one if missing
  const correlationId = incomingCorrelationId || randomUUID();

  // 3. create request context
  withRequestContext({}, () => {
    // 3.1 Store correlation id in request context
    requestContext.set('correlationId', correlationId);
    //3.2 Return correlation id to the client
    res.setHeader(CORRELATION_ID_HEADER, correlationId);
    //3.3 Start processing the request with the request context
    next();
  });
}
